### PR TITLE
[RangeDateField] Changing the component name and interface name "Period" to "DateRange", also fixing a bug on resize and adjusting min and max date props

### LINKED ISSUE #551: [RangeDateField] Fixing bugs when resize the component and adjusting some calendar behaviors

### PR DESCRIPTION
**Pull request by gustavomoser**
closes #551

### CODE REVIEW

File: src/components/RangeDateField/BaseRangeDateInput.tsx [hunk 1]
```diff
@@ -5,19 +5,19 @@ import { useLocale } from '../../i18n'
 import { ExternalStyles, focusBoxShadow, Theme, useStyles } from '../../styles'
 import { composeRefs } from '../../util/react'
 import { DateInput } from '../DateField'
-import { Icons } from '../Icon'
-import { InputWrapper } from '../TextField/InputWrapper'
+import { Icons, Icon } from '../Icon'
+import { Button } from '..'
 
-export interface Period {
+export interface RangeDate {
```
Comment (fliptaboada) [inline src/components/RangeDateField/BaseRangeDateInput.tsx]: `DateRange` might be a better name for this type and the components.

File: src/components/RangeDateField/BaseRangeDateInput.tsx [hunk 2]
```diff
@@ -5,19 +5,19 @@ import { useLocale } from '../../i18n'
...
   startDate?: Date
   finalDate?: Date
```
Comment (fliptaboada) [inline src/components/RangeDateField/BaseRangeDateInput.tsx]: Also I think `endDate` is better here.

File: src/components/Calendar/RangeCalendar/DateRangeCalendar/DateRangeCalendar.tsx [hunk 3]
```diff
@@ -0,0 +1,85 @@
+import * as React from 'react'
+
+import { Theme } from '../../../../styles'
+import { CalendarProps } from '../../Calendar'
+import { isSameDay } from '../../util'
+import { GenericRangeCalendar } from '../GenericRangeCalendar/GenericRangeCalendar'
+
+export interface DateRangeCalendarProps extends CalendarProps {
+  initialDate: Date
+  finalDate: Date
```
Comment (fliptaboada) [inline src/components/Calendar/RangeCalendar/DateRangeCalendar/DateRangeCalendar.tsx]: maybe we should rename this to match `DateRange`, `startDate` and `endDate`?
