### PR TITLE
864 - [Tick] The component is receving not recognize props causing a console warning

### LINKED ISSUE #864: [Tick] The component is receving not recognize props causing a console warning
# Create a bug report to help us improve Bold 💪

Depends on:
- #863 

### **Describe the bug**
The component is having problems with not recognize props, as "vertichalAnchor" and "visibleTickCount"

### **To Reproduce**
1. Using the component Tick calling inside a Chart Component
 
### **Expected behavior**
Do not throw warning console to a not recognize props
 
### **Screenshots**
Image

### PR DESCRIPTION
**Pull request by AndresKindel**
depends on #863
closes #864

### CODE REVIEW

File: src/components/Chart/renderAxis.tsx [hunk 1]
```diff
@@ -139,8 +144,7 @@ function getAxisProps(
     }
 }
 
-// TODO: Talvez o problema da outra issue esteja aquitalvez o problema esteja aqui
-const convertTickProps = (props: any): TickProps => ({
+export const convertTickProps = (props: any): TickProps => ({
```
Comment (wesleydecezere) [inline src/components/Chart/renderAxis.tsx:147]: Since it is now being used by more than one file, it could be moved to a common file, like `util.ts` or `model.ts`

**Review by wesleydecezere — APPROVED** [review]

**Review by wagnerbsantos — DISMISSED** [review]

**Review by GuilhermePrandi — APPROVED** [review]

File: src/components/Chart/renderAxis.tsx (hunk 1 above)
Comment (zDudaHang) [reply src/components/Chart/renderAxis.tsx:147]: :point_up:

**Review by zDudaHang — DISMISSED** [review]

File: src/components/Chart/renderAxis.tsx (hunk 1 above)
Comment (Andrevmatias) [reply src/components/Chart/renderAxis.tsx:147]: Seems good. Just remember to follow the bold code patterns, not the PEC ones.

**Review by Andrevmatias — APPROVED** [review]
Thank you! :blush:

**Review by carolinapsil — APPROVED** [review]
