### PR TITLE
861 - The component does not have a red border

### LINKED ISSUE #861: [MonthRangePicker] The component does not have a red border
# Create a bug report to help us improve Bold 💪

### **Describe the bug**
The component does not have a red border when the prop `error` is defined.

### **To Reproduce**
1. Add a value to `error` prop
2. The border stills gray
 
### **Expected behavior**
The border must be red  when the prop `error` is defined.
 
### **Screenshots**
Screenshot from 2024-10-11 11-37-52

### PR DESCRIPTION
**Pull request by zDudaHang**
closes #861

### CODE REVIEW

File: src/components/MonthRangePicker/MonthRangePickerInput.tsx [hunk 1]
```diff
@@ -13,7 +13,7 @@ export function MonthRangePickerInput(props: MonthRangePickerInputProps) {
 
   return (
     <FormControl {...getFormControlProps()}>
-      <BaseMonthRangeInput {...inputProps} {...rest} />
+      <BaseMonthRangeInput invalid={inputProps['aria-invalid']} {...inputProps} {...rest} />
```
Comment (wesleydecezere) [inline src/components/MonthRangePicker/MonthRangePickerInput.tsx:16]: Does the aria-invalid property need to remain in inputProps, since it has already been used elsewhere?

File: src/components/MonthRangePicker/MonthRangePicker.stories.tsx [hunk 2]
```diff
@@ -1,37 +1,99 @@
...
+      disabled={boolean('disabled', false)}
+      value={range}
+    />
+  )
+}
+
+export const MinMax = () => {
+  const [range, setRange] = useState<ReferenceMonthRange>(initialValue)
+
+  const handleChange = (dateRange: DateRange) => {
```
Comment (wesleydecezere) [inline src/components/MonthRangePicker/MonthRangePicker.stories.tsx:63]:
```suggestion
  const handleRangeChange = (setRange) => (dateRange: DateRange) => {
```
You could declare this function at the file scope and reuse it within the component scope

**Review by wesleydecezere — COMMENTED** [review]
🚀

**Review by wesleydecezere — APPROVED** [review]

**Review by wesleydecezere — APPROVED** [review]

File: src/components/MonthRangePicker/MonthRangePickerInput.tsx (hunk 1 above)
Comment (zDudaHang) [reply src/components/MonthRangePicker/MonthRangePickerInput.tsx:16]: Oh, now i understand hehe
