### PR TITLE
942 - [Modal] Tooltip is rendering below the modal 

### LINKED ISSUE #942: [Modal] Tooltip is rendering below the modal
### **Describe the bug**

When `depthLevel` is `3` or higher, the tooltip is rendered below the modal.
 
### **To Reproduce**

1. Go to Modal stories file
2. Set `depthLevel` as 3 or higher
3. Hover the close button
4. See the tooltip rendering below the modal
 
### **Expected behavior**

The tooltip should render above the modal
 
### **Additional context**

I believe the same problem may be happening with poppers and dropdowns if used within the modal.

### PR DESCRIPTION
**Pull request by AndresKindel**
closes #942

I updated the tooltip's zIndex to be higher than all the modal's zIndex levels, so it will never have a lower zIndex. From what I've seen, the issue doesn't occur with the popper or the dropdown.

### CODE REVIEW

**Review by ykr337 — DISMISSED** [review]

File: src/styles/theme/zIndex.ts [hunk 1]
```diff
@@ -7,7 +7,7 @@ export interface ZIndex {
 export const zIndex: ZIndex = {
   popper: 1200,
   dropdown: 1300,
-  tooltip: 1400,
+  tooltip: 2000,
```
Comment (lucasjoao) [inline src/styles/theme/zIndex.ts:10]: The snapshot in `Tooltip.test.tsx` confirms that the CSS output is 2000, but it doesn't guarantee that this value is actually higher than every modalContainer. A value like `tooltip: 1800` would still pass the test just fine.

We've run into this before. PR #527 fixed a hardcoded in DateField, and PR #612 introduced the five modal levels but left the tooltip at 1400.

Let's try create a new test file at `src/styles/theme/zIndex.test.ts`:

```TypeScript
it('tooltip z-index must exceed the highest modal container level', () => {
  const maxModalContainer = Math.max(
    ...Object.values(zIndexLevel).map((z) => z.modalContainer)
  )
  expect(zIndex.tooltip).toBeGreaterThan(maxModalContainer)
})
```

This way, if someone adds a depthLevel 6 in the future without updating the tooltip's z-index, the CI will catch it and break immediately.

**Review by lucasjoao — CHANGES_REQUESTED** [review]
Just one thing that could help us in the future.

File: src/styles/theme/zIndex.ts (hunk 1 above)
Comment (AndresKindel) [reply src/styles/theme/zIndex.ts:10]: Nice! I didn't think of that, it makes total sense :)

**Review by lucasjoao — APPROVED** [review]
:top: :100: :rocket:
