### PR TITLE
988 - CI pipeline failure due to outdated dependencies

### LINKED ISSUE #988: CI pipeline failure due to outdated dependencies
Currently, the CI pipeline is failing during the visual regression testing step. The initial error occurs because the old version of Loki (v0.27.0) tries to pull a specific Docker image for Headless Chrome (yukinying/chrome-headless-browser) and fails with a timeout error (Client.Timeout exceeded while awaiting headers).

Since this Loki version is very old, the infrastructure it tries to access no longer responds correctly in the GitHub Actions environment. To fix this, it will be necessary to update the Loki version, which consequently requires to update several other libraries to keep the ecosystem compatible.

Image

### PR DESCRIPTION
**Pull request by AndresKindel**
closes #988

The main goal of this Pull Request is to fix the CI pipeline failures. To solve this issue, the Loki version was updated, which triggered a series of necessary updates. I updated the versions of Storybook, Webpack, Babel, TypeScript, and Node, replaced the outdated awesome-typescript-loader with ts-loader, and updated the site's Gatsby version.

### CODE REVIEW

File: .storybook/preview.js [hunk 1]
```diff
@@ -11,26 +8,11 @@ if (process.env.STORYBOOK_LOKI) {
...
-      },
-      infoPage: {
-        padding: '0 5px 0 5px',
-      },
-      infoStory: {
-        padding: '0 45px 0 45px',
-      },
+  docs: {
+    canvas: {
+      sourceState: 'shown',
```
Comment (ykr337) [inline .storybook/preview.js:13]: where are these parameters now? Aren't they necessary anymore?

File: webpack.config.js [hunk 2]
```diff
@@ -23,23 +22,25 @@ const config = {
   module: {
     rules: [
       {
-        loader: 'awesome-typescript-loader',
         test: /\.tsx?$/,
+        loader: 'ts-loader',
```
Comment (ykr337) [inline webpack.config.js:26]: the previous value don't exist anymore?

File: webpack.config.js [hunk 3]
```diff
@@ -23,23 +22,25 @@ const config = {
...
         test: /\.css$/,
+        type: 'asset/source',
       },
     ],
   },
-  plugins: [new CheckerPlugin()],
-  externals: ['react', 'react-dom'],
+  externals: {
+    react: 'react',
+    'react-dom': 'react-dom',
```
Comment (ykr337) [inline webpack.config.js:37]: is that correct? The first react-dom should not use ' i belive

File: .storybook/preview.js (hunk 1 above)
Comment (AndresKindel) [reply .storybook/preview.js:13]: this part was the configuration for the @storybook/addon-info addon, which generated simple documentation from the component's code. This addon is no longer maintained and its function is now handled by @storybook/addon-essentials, so that configuration is no longer necessary.

File: webpack.config.js (hunk 2 above)
Comment (AndresKindel) [reply webpack.config.js:26]: awesome-typescript-loader is no longer maintained, so it was removed and replaced with ts-loader

File: webpack.config.js (hunk 3 above)
Comment (AndresKindel) [reply webpack.config.js:37]: it is required because of the hyphen in react-dom

**Review by Ishunter — DISMISSED** [review]

**Review by Livia-ferrao — DISMISSED** [review]

File: site/package.json [hunk 4]
```diff
@@ -13,19 +13,19 @@
     "prebuild": "yarn install"
   },
   "dependencies": {
-    "@mdx-js/mdx": "1.5.5",
-    "@mdx-js/react": "1.5.5",
+    "@mdx-js/mdx": "^1.6.22",
```
Comment (lucasjoao) [inline site/package.json]: Please pin the dependency versions. Using ^ can lead to unexpected issues with sub-dependencies.

File: src/components/PivotTable/Draggable/DraggableRow.tsx [hunk 5]
```diff
@@ -18,7 +18,11 @@ export function DraggableRow<T>(props: DraggableRowProps<T>) {
 
   if (value && value.length > 0) {
     return (
-      <DropdownItem key={name + value} className={classes.dropdownItem} aria-checked={selected ? 'true' : 'false'}>
+      <DropdownItem
+        key={name.toString() + value}
```
Comment (lucasjoao) [inline src/components/PivotTable/Draggable/DraggableRow.tsx:22]: Why this change?

File: tsconfig.json [hunk 6]
```diff
@@ -15,7 +15,8 @@
     "allowSyntheticDefaultImports": true,
     "strict": true,
     "strictNullChecks": false,
-    "noImplicitAny": false
+    "noImplicitAny": false,
+    "skipLibCheck": true
```
Comment (lucasjoao) [inline tsconfig.json:19]: Why this change?

File: package.json [hunk 7]
```diff
@@ -5,7 +5,7 @@
   "types": "lib/index.d.ts",
   "homepage": "https://bold.bridge.ufsc.br",
   "engines": {
-    "node": ">=14"
+    "node": ">=22"
```
Comment (lucasjoao) [inline package.json]: This appears to be a breaking change for bold-ui consumers. 

Have you tested this against an e-sus 5.4.x? 

I'm concerned the new Node version could break something in that environment.

File: package.json [hunk 8]
```diff
@@ -68,14 +68,13 @@
...
   "devDependencies": {
-    "@babel/core": "7.10.3",
-    "@storybook/addon-a11y": "6.1.11",
-    "@storybook/addon-actions": "6.1.11",
-    "@storybook/addon-info": "6.0.0-alpha.2",
-    "@storybook/addon-knobs": "6.1.11",
-    "@storybook/addons": "6.1.11",
-    "@storybook/core": "6.1.11",
-    "@storybook/react": "6.1.11",
+    "@babel/core": "^7.29.0",
```
Comment (lucasjoao) [inline package.json]: See the other thread about ^.

File: site/package.json [hunk 9]
```diff
@@ -13,19 +13,19 @@
...
+    "@mdx-js/react": "^1.6.22",
     "bold-ui": "file:../src",
     "docsearch.js": "2.6.3",
-    "gatsby": "^2.32.4",
+    "gatsby": "^3.15.0",
```
Comment (lucasjoao) [inline site/package.json]: Are you sure these gatsby versions are compatible with each other?

The AI that assisted me with this review flagged the following:

_- [site/package.json:22-26] — Incompatibilidade de versões de plugins Gatsby. O site usa gatsby: ^3.15.0 mas declara gatsby-plugin-typescript: ^5.16.0 (feito para Gatsby 5) e gatsby-plugin-react-helmet: ^6.16.0 (feito para Gatsby 4+). Para Gatsby 3, as versões corretas são ^3.15.0 e ^4.x, respectivamente. O site/yarn.lock confirma o conflito com duas versões do mesmo plugin resolvidas simultaneamente. Se o objetivo for ir para Gatsby 4 ou 5, é necessária uma migração completa — não um bump parcial de plugins._

File: package.json [hunk 10]
```diff
@@ -120,13 +119,15 @@
     "react-docgen-typescript-loader": "3.7.2",
     "react-dom": "16.13.1",
     "react-test-renderer": "16.13.1",
+    "storybook": "7.6.24",
     "terser-webpack-plugin": "^4.2.3",
```
Comment (lucasjoao) [inline package.json:122]: Is this still needed?

File: .storybook/preview.js [hunk 11]
```diff
@@ -11,26 +8,11 @@ if (process.env.STORYBOOK_LOKI) {
...
     },
   },
 }
 
-const allDecorators = [withA11y, withKnobs, withStorybookTheme]
```
Comment (lucasjoao) [inline .storybook/preview.js:34]: If we remove withKnobs from the global decorators, we might break stories that rely on it without an explicit local declaration, like [this one](https://github.com/laboratoriobridge/bold/blob/fix-loki/src/components/Number/Number.stories.tsx#L1). Should we check if those stories need updates?

**Review by lucasjoao — CHANGES_REQUESTED** [review]
Great work on this! Thanks for taking the initiative.

I have some points that need to be cleared up before moving forward with the merge

File: src/components/PivotTable/Draggable/DraggableRow.tsx (hunk 5 above)
Comment (AndresKindel) [reply src/components/PivotTable/Draggable/DraggableRow.tsx:22]: After the TypeScript version update, this started causing a build error. name is of type keyof T and value is a string. From what I understand, TypeScript previously assumed name was a string and allowed the concatenation, but that's no longer the case

File: tsconfig.json (hunk 6 above)
Comment (AndresKindel) [reply tsconfig.json:19]: The issue here is that `@storybook/addon-knobs` is officially deprecated and no longer maintained, which is causing some typescript errors inside its `node_modules` folder during the `yarn build`. Enabling `skipLibCheck` is the workaround I found for now. I've tested storybook locally and everything is rendering perfectly, though I know relying on `skipLibCheck` might not be the ideal long-term solution.

The current standard is `@storybook/addon-controls`. However, migrating to it requires a completely different approach (using args instead of inline functions). Since this means we'd have to refactor basically every single `.stories` file in the project, I think it would be safer to handle this migration in a separate, dedicated issue to avoid bloating this one.

What do you think? 🤔

File: package.json (hunk 7 above)
Comment (AndresKindel) [reply package.json]: I haven't been able to test it on esus 5.4.x. I'm running into some build errors, but from what I've seen, the same thing is happening on bold's main branch (or maybe I'm just doing something wrong) 😢

File: site/package.json (hunk 9 above)
Comment (AndresKindel) [reply site/package.json]: From what I can tell, they really are incompatible. It wasn't causing any issues with the site, but just to be safe, I downgraded to the recommended versions.

File: .storybook/preview.js (hunk 11 above)
Comment (AndresKindel) [reply .storybook/preview.js:34]: I tested it, and it seems like withKnobs isn't necessary. All the stories I checked are behaving exactly the same as before 🙏

File: package.json (hunk 10 above)
Comment (AndresKindel) [reply package.json:122]: tested it without it and it doesn't work, it seems like it's required in the newer versions.

File: tsconfig.json (hunk 6 above)
Comment (lucasjoao) [reply tsconfig.json:19]: I agree with you.

File: package.json (hunk 7 above)
Comment (lucasjoao) [reply package.json]: This test is a requirement for merging. I've found an old tutorial [here](https://laboratoriobridge.slack.com/archives/C025JKPML3E/p1639589103036500) that might help you set it up.

File: tsconfig.json (hunk 6 above)
Comment (lucasjoao) [reply tsconfig.json:19]: Can you create the new issue?

File: .storybook/preview.js (hunk 11 above)
Comment (lucasjoao) [reply .storybook/preview.js:34]: According to the official v8 documentation, withKnobs is still required as a decorator. The README explicitly states it must be registered either per story or as a global decorator:

https://github.com/storybookjs/addon-knobs?tab=readme-ov-file#getting-started

To be sure this is working correctly, could you open a story that uses knob functions (e.g.` src/components/Number/Number.stories.tsx)` and verify two things: (1) the Knobs panel appears in the Storybook UI addons panel, and (2) changing a knob value actually updates the rendered component? If the decorator is truly not needed anymore, that would be great news, but I want to make sure we have evidence beyond visual similarity, since the Loki reference images were generated after the removal and would encode a broken state without us noticing.

**Review by lucasjoao — CHANGES_REQUESTED** [review]

File: tsconfig.json (hunk 6 above)
Comment (AndresKindel) [reply tsconfig.json:19]: Done :) https://github.com/laboratoriobridge/bold/issues/989

File: package.json (hunk 7 above)
Comment (AndresKindel) [reply package.json]: I followed the tutorial and managed to test it on 5.4; everything ran smoothly without any issues. But, just to be sure, I went to test it on 5.5 again and ran into some problems. I did some research and saw it could be a yarn link issue, which led me to [yalc](https://github.com/wclr/yalc). Using it, I was able to test on both 5.4 and 5.5, and it looks like everything is working perfectly now :pray:
I also noticed that after some changes, Node 22 is no longer required, so I downgraded to 16 to avoid any issues.

File: .storybook/preview.js (hunk 11 above)
Comment (AndresKindel) [reply .storybook/preview.js:34]: I already ran those tests you mentioned on a few stories, and they all still have the Knobs panel and responded to the changes made there. I have no idea why it's working, but it is :sweat_smile:
Anyway, Knobs is going to be replaced in https://github.com/laboratoriobridge/bold/issues/989, so I don't see an issue

File: webpack.config.js [hunk 12]
```diff
@@ -23,23 +22,25 @@ const config = {
...
+  },
   optimization: {
     minimize: true,
     minimizer: [
       new TerserPlugin({
         terserOptions: {
-          sourceMap: true,
```
Comment (Andrevmatias) [inline webpack.config.js:42]: Are the source maps still being generated? they are very important for debugging.

**Review by Andrevmatias — DISMISSED** [review]
Great! Seems good, just make sure the site and its publishing workflow are still working.

File: webpack.config.js (hunk 12 above)
Comment (AndresKindel) [reply webpack.config.js:42]: Yes! That terserOptions option has been deprecated. Now all you need is that `devtool: 'source-map'` on line 21 :)

**Review by lucasjoao — DISMISSED** [review]
:top: :100: :rocket:

**Review by diegoasmello — DISMISSED** [review]
🚀🚀 🚀

**Review by ykr337 — APPROVED** [review]
